apiVersion: v1
kind: Service
metadata:
  name: itm-fre-all-svc
  namespace: itm-fre-all-nms
  labels:
    app: interviewmaster
    version: v1.0.0
    tier: frontend
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: interviewmaster
    version: v1.0.0
    tier: frontend
  type: ClusterIP
