apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  creationTimestamp: null
  name: itm-fre-hpa
  namespace: itm-fre-all-nms
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: itm-fre-all-dpl
  targetCPUUtilizationPercentage: 50