kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ebs-sc
  namespace: istio-system
allowVolumeExpansion: false
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: gp3
  allowAutoIOPSPerGBIncrease: 'true'
