apiVersion: apps/v1
kind: Deployment
metadata:
  name: itm-bce-dbr-dpl
  namespace: itm-bce-dbr-nms
spec:
  replicas: 2
  selector:
    matchLabels:
      app: interviewmaster
  template:
    metadata:
      labels:
        app: interviewmaster
        version: v1.0.0
        tier: backend
    spec:
      serviceAccountName: itm-eks-dbr-sa
      containers:
      - image: jongik0217/itm-aws-dbr:1.05
        name: itm-bce-dbr
        ports:
        - containerPort: 8000
        env:
        - name: env
          value: eks
        envFrom:
        - configMapRef:
            name: itm-bce-dbr-cmp
        - secretRef:
            name: itm-bce-dbr-scr
---
apiVersion: v1
kind: Service
metadata:
  name: itm-bce-dbr-svc
  namespace: itm-bce-dbr-nms
  labels:
    app: interviewmaster
    version: v1.0
    tier: backend
spec:
  type: NodePort
  selector:
    app: interviewmaster
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30000