apiVersion: v1
kind: ConfigMap
metadata:
  namespace: itm-bce-dbr-nms
  name: itm-bce-dbr-cmp
  labels:
    app: interviewmaster
data:
  AWS_REGION: "ap-northeast-2"
  DB_READ_LOC_URI: "mongodb://192.168.56.100:32018/?replicaSet=rs0&directConnection=true"
  DB_READ_K8S_URI: "mongodb://itm-dtb-mng-svc.itm-dtb-mng-nms.svc.cluster.local:27017/?replicaSet=rs0&readPreference=secondary"
  DB_WRITE_LOC_URI: "mongodb://192.168.56.100:32017/?replicaSet=rs0&directConnection=true"
  DB_WRITE_K8S_URI: "mongodb://itm-dtb-mng-svc.itm-dtb-mng-nms.svc.cluster.local:27017/?replicaSet=rs0&readPreference=secondary"
  DB_CHECK_LOC_URI: "http://192.168.0.34:3000"
  DB_CHECK_K8S_URI: "http://192.168.0.22:30803"
  DB_CHECK_EKS_URI: "https://interviewmaster.store"
  KAKAO_REDIRECT_LOC_URI: "http://192.168.0.66:8000/act/kakao/auth"
  KAKAO_REDIRECT_K8S_URI: "http://192.168.0.22:30803/dbr/act/kakao/auth"
  KAKAO_REDIRECT_EKS_URI: "https://interviewmaster.store/dbr/act/kakao/auth"
  KAKAO_SCOPE: "openid,account_email"
  OTEL_ENDPOINT_URL: "http://opentelemetry-collector.istio-system.svc.cluster.local:4317"
  OTEL_PYTHON_LOG_CORRELATION: "true"
  OTEL_PYTHON_LOG_FORMAT: "%(pathname)s:%(funcName)s:%(lineno)d:%(levelname)s:%(message)s"
  OTEL_RESOURCE_ATTRIBUTES: "service.instance.id=production,service.name=itm.bce.dbr,telemetry.sdk.name=opentelemetry,telemetry.sdk.language=python,telemetry.sdk.version=1.18.0"
  DEBUG_LOG_OTEL_TO_CONSOLE: "true"
  DEBUG_LOG_OTEL_TO_PROVIDER: "true"
  OTEL_PYTHON_LOG_LEVEL: "info"