# StatefulSet이 뜨면서 자동으로 PVC생성해줌
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: itm-dtb-mng-sts
  namespace: itm-dtb-mng-nms
spec:
  serviceName: itm-dtb-mng-svc
  replicas: 3
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - mongodb
            topologyKey: "kubernetes.io/hostname"
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                  - worker1
                  - worker2
                  - worker3
      containers:
      - name: mongodb
        image: mongo:5.0.0
        ports:
        - containerPort: 27017
        command:
        - "mongod"
        - "--bind_ip"
        - "0.0.0.0"
        - "--replSet"
        - "rs0"
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongodb-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
      storageClassName: openebs-hostpath
---
# BACK에서 다이렉트로 접속하기 위한 svc
apiVersion: v1
kind: Service
metadata:
  name: itm-dtb-mng-svc
  namespace: itm-dtb-mng-nms
  labels:
    app: mongodb
    version: v1.0
    tier: database
spec:
  type: ClusterIP
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017
---
# PRIMARY MongoDB에 다이렉트로 접속하기 위한 svc
apiVersion: v1
kind: Service
metadata:
  name: itm-dtb-prm-svc
  namespace: itm-dtb-mng-nms
  labels:
    app: mongodb
    version: v1.0
    tier: database
    statefulset.kubernetes.io/pod-name: itm-dtb-mng-sts-0
spec:
  type: NodePort
  selector:
    app: mongodb
    statefulset.kubernetes.io/pod-name: itm-dtb-mng-sts-0
  ports:
  - port: 27017
    targetPort: 27017
    nodePort: 32017
---
# SECONDARY MongoDB에 다이렉트로 접속하기 위한 svc
apiVersion: v1
kind: Service
metadata:
  name: itm-dtb-sc1-svc
  namespace: itm-dtb-mng-nms
  labels:
    app: mongodb
    version: v1.0
    tier: database
    statefulset.kubernetes.io/pod-name: itm-dtb-mng-sts-1
spec:
  type: NodePort
  selector:
    app: mongodb
    statefulset.kubernetes.io/pod-name: itm-dtb-mng-sts-1
  ports:
  - port: 27017
    targetPort: 27017
    nodePort: 32018
---
# SECONDARY MongoDB에 다이렉트로 접속하기 위한 svc
apiVersion: v1
kind: Service
metadata:
  name: itm-dtb-sc2-svc
  namespace: itm-dtb-mng-nms
  labels:
    app: mongodb
    version: v1.0
    tier: database
    statefulset.kubernetes.io/pod-name: itm-dtb-mng-sts-2
spec:
  type: NodePort
  selector:
    app: mongodb
    statefulset.kubernetes.io/pod-name: itm-dtb-mng-sts-2
  ports:
  - port: 27017
    targetPort: 27017
    nodePort: 32019

